# Generated by Django 2.2.3 on 2019-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
