# Generated by Django 2.2.3 on 2019-07-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0002_league_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('departure', models.DateTimeField()),
                ('voyage', models.CharField(max_length=255)),
                ('arrival', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('place', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
