# Generated by Django 2.2.3 on 2019-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0003_busstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='arrival',
            field=models.TimeField(),
        ),
    ]
