# Generated by Django 2.2.3 on 2019-07-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0004_auto_20190722_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busstation',
            unique_together={('title', 'departure', 'voyage')},
        ),
    ]
