# Generated by Django 2.2.3 on 2019-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0005_auto_20190723_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
