# Generated by Django 2.2.3 on 2019-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0007_auto_20190725_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='country',
        ),
        migrations.RemoveField(
            model_name='match',
            name='country',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
