# Generated by Django 2.2.3 on 2019-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0008_auto_20190726_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('spider_name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
