# Generated by Django 2.2.3 on 2019-07-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0009_scraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='job_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='project_name',
            field=models.CharField(default='bus_scrapy', max_length=255),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='spider_name',
            field=models.CharField(default='busscrapy', max_length=255),
        ),
    ]
