# Generated by Django 2.2.3 on 2019-07-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0010_auto_20190726_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='last_checked',
        ),
    ]
